server:
  port: 8080

# Swagger/문서화 끄기(운영)
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}

# Cognito(prod) — 전부 환경변수/Secrets로
app:
  cognito:
    region: ${COGNITO_REGION}
    user-pool-id: ${COGNITO_USER_POOL_ID}
    client-id: ${COGNITO_CLIENT_ID}
    user-info-uri: ${COGNITO_USER_INFO_URI}
  cors:
    allowed-origins: "https://kickytime.nextcloudlab.com"